# Generated by Django 2.2.2 on 2019-06-25 17:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import os 
import csv 

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [

    ]