# Generated by Django 2.2.2 on 2019-06-25 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import os 
import csv 

def read_data(apps, schema_editor):
    Book = apps.get_model('catalog', 'Book')

    filename = os.path.join(settings.BASE_DIR, 'sample_books.csv')

    with open(filename) as csvfile:
        reader = csv.DictReader(csvfile)

        for row in reader:

            book = Book(
                title = row['title'],
                author = row['author'],
                url = row['url'],
                summary = row['description']
            )
            
            book.save()

def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book'),
    ]

    operations = [
        migrations.RunPython(read_data, do_nothing)
    ]
    